### ISSUE TITLE
 To use lscpus with version 4.x and above you need to set the domain name variable:  STREAMS_DOMAIN_ID

### ISSUE THREAD

**Issue by StanBury** [IBMStreams/streamsx.utility#11]
Please add this information to the README:

 To use lscpus with Streams version 4.x and above you need to set the domain name variable:  STREAMS_DOMAIN_ID

Thanks,  Stan

**Comment by scotts** [comment]
Resolved with pull request #14. The option is now supported on the command line, and the README notes that if that option is not provided, it will use the environment variable.
