### ISSUE TITLE
Do not disable insecure requests warnings by default.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.utility#24]
https://github.com/IBMStreams/streamsx.utility/blob/master/python/packages/streamsx/rest.py#L13

Should be up to the app using a generic library if it wants to disable warnings or not.

**Comment by ibmkendrick** [comment]
I'll work on this one.

**Comment by ibmkendrick** [comment]
Need to add mechanism to allow user to provide their own certificates or disable SSL certificate checks.

**Comment by ibmkendrick** [comment]
If user wants to bypass SSL verification, then:
1. create a `StreamsConnection` object, specifying `verify=False`
2. add it to config[ConfigPararms.STREAMS_CONNECTION]

**Comment by ibmkendrick** [comment]
Going to wait for the REST APIs to merge with streamsx.topology before delivering the fix, as the fix will requires changes in both modules.

**Comment by ddebrunner** [comment]
Replaced by:

https://github.com/IBMStreams/streamsx.topology/issues/857
