### ISSUE TITLE
[Python] Support for getting a list of views, and getting a list of views by name.

### ISSUE THREAD

**Issue by wmarshall484** [IBMStreams/streamsx.utility#28]

**Comment by wmarshall484** [comment]
TODO: since views all have different physical names (e.g., instancee34f9daad::job02::myView), but can have the same logical names (myView), the `retrieve_view(str)` method should return a list. Currently it just finds the first view encountered.

Maybe we should support a way of finding a view based on the physical name, such as searching for a view within a particular instance or job.

**Comment by ddebrunner** [comment]
Replaced by:
https://github.com/IBMStreams/streamsx.topology/issues/856
