### ISSUE TITLE
Remove streamsx.rest.VcapUtils.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.utility#33]
Simply have private functions to get vcap info that are used by code within `streamsx`.

**Comment by ddebrunner** [comment]
Also only pass in the vcap info and service name as parameters, no need to complicate with a config object.

**Comment by wmarshall484** [comment]
Currently working on this. Can't be assigned as I am not a member of the project.

**Comment by ddebrunner** [comment]
Fixed after a couple of reverts with #46
