### ISSUE TITLE
Python: Add the ability to refresh any REST object to get the latest state.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.utility#38]
E.g. refresh a job to get its latest health.

Code should be generic.

**Comment by ibmkendrick** [comment]
I'm working on this one.

**Comment by ibmkendrick** [comment]
When the REST call to refresh status returns successfully, the shape of the JSON response should be identical (i.e. contains identical set of keys).

When the REST call returns an error, the JSON attributes stored within `_ResourceElement` object should be reflected accordingly.  (for example, if a job has been cancelled, then the `job.health` should indicate so)

Different objects may have different ways to represent error state, and will need to be processed accordingly.

**Comment by ddebrunner** [comment]
Replaced by:

https://github.com/IBMStreams/streamsx.topology/issues/862
